name: 'ğŸ·ï¸ Conventional release labels'

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write    # â¬…ï¸ necesario para que funcione la Action
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: '{"feat": "ğŸš€ Feature", "fix": "ğŸ•µğŸ» Fix", "breaking": "âš ï¸ Breaking Change"}'

#         with:
#   type_labels: |
#     {
#       "feat": "ğŸš€ Feature", 
#       "fix": "ğŸ› Bug Fix",
#       "docs": "ğŸ“ Documentation",
#       "style": "ğŸ’… Style",
#       "refactor": "â™»ï¸ Refactor",
#       "perf": "âš¡ Performance",
#       "test": "ğŸ§ª Tests",
#       "build": "ğŸ“¦ Build",
#       "ci": "ğŸ”§ CI/CD",
#       "chore": "ğŸ§¹ Chore",
#       "revert": "âª Revert",
#       "breaking": "âš ï¸ Breaking Change"
#     }