name: 'ðŸ¢ Next.js'

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›¬
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache node_modules ðŸ§ 
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Setup Node âš™ï¸
        uses: actions/setup-node@v4
        with:
          node-version: 22.5

      - name: Install dependencies ðŸ“©
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Next.js ðŸ“¦
        run: npm run build

      - name: Lint code ðŸ’…
        run: npm run lint

      - name: Setup Playwright ðŸ§ª
        run: npx playwright install --with-deps

      - name: Start Next.js server ðŸš€
        run: |
          npm run start &
          echo $! > next.pid
        env:
          PORT: 3000

      - name: Run Playwright tests âœ…
        run: npm run test

      - name: Stop Next.js server ðŸ›‘
        run: |
          kill $(cat next.pid) || true

      - name: Cache Next.js build âš¡
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ hashFiles('package-lock.json') }}
